In [3]:
import warnings
import cv2
import os
import copy
from sklearn.externals import joblib
import numpy as np
from keras.models import load_model

C:\Users\bruce0809\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [4]:
model = load_model('CNN_model(small).h5')

cascade_file = 'haarcascade_frontface.xml'
cascade = cv2.CascadeClassifier(cascade_file)

capture = cv2.VideoCapture(0)    # n은 장치번호
capture.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
frame_count = 0

while True:
    ret, frame = capture.read()  # ret==카메라상태 저장, 정상작동은 True 반환
                                 # frame== 현재프레임 저장
    frame2 = copy.copy(frame)
    frame_count += 1
    
    # 이전 프레임과 비교를 위해 흑백으로 변환하기 --- (*2)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    face_list = cascade.detectMultiScale(gray)

    if len(face_list) == 0:
        quit()
         
    for (x,y,w,h) in face_list:
        roi = frame[y:y+h, x:x+w]
        imagex = cv2.resize(roi, (200, 200))
        print(imagex.shape)
        image_data = imagex.reshape(1, 200, 200,3 )
    
        color = (255, 0, 0)
    
        pred_y = model.predict(image_data) # --- (*4)
        print(pred_y)
        
        if np.argmax(pred_y) == 0:
                cv2.rectangle(frame, (x, y), (x+w, y+h), color, thickness=4)
                cv2.putText(frame,'Positive',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))  
                
        elif np.argmax(pred_y) == 1:  
                cv2.rectangle(frame, (x, y), (x+w, y+h), color, thickness=4)
                cv2.putText(frame,'Neutral',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))  
        else:
            np.argmax(pred_y) == 2
            cv2.rectangle(frame, (x, y), (x+w, y+h), color, thickness=4)
            cv2.putText(frame,'Negative',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))          
        
    cv2.imshow("VideoFrame", frame) # 윈도우 창에 이미지 띄움
    if cv2.waitKey(1) > 0:       # (time) 은 time 마다 키 입력상태 받아옴
        break   

capture.release()                # 받아온 메모리 해제
cv2.destroyAllWindows()          # 모든 윈도우 창 닫기

(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[4.0824611e-07 0.0000000e+00 9.9999964e-01]]
(200, 200, 3)
[[1.1353641e-37 0.0000000e+00 1.0000000e+00]]
(200, 200, 3)
[[2.5990522e-07 0.0000000e+00 9.9999976e-01]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[1. 0. 0.]]
(200, 200, 3)
[[1.0000000e+00 5.6486556e-17 0.0000000e+00]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[0. 0. 1.]]
(200, 200, 3)
[[7.3439558e-22 2.9518417e-35 1.0000000e+00]